name: Test GIO using PnetCDF with MPICH and OpenMPI

permissions:
  contents: read

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.1'
      - '**/*.jpg'
      - '**/*.png'
      - 'docs/*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.1'
      - '**/*.jpg'
      - '**/*.png'
      - 'docs/*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Enable manual run'
        required: false
        default: 'Manual trigger'

env:
   LIBTOOL_VERSION: 2.5.4
   MPICH_VERSION: 5.0.1
   OPENMPI_VERSION: 5.0.9
   # PNETCDF_REPO: Parallel-NetCDF
   PNETCDF_REPO: wkliao

jobs:
    build:
      strategy:
        fail-fast: false # This disables the default cancel-on-failure behavior
        matrix:
          os: [ubuntu-latest]               # [ubuntu-latest, macos-latest]
          mpi_vendor: [ MPICH ]             # [ MPICH, OpenMPI ]
          fstype: [ ufs, mimic_lustre ]
          debug_mode: [ nodebug ]           # [ debug, nodebug ]

      runs-on: ${{ matrix.os }}
      timeout-minutes: 120

      steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

        - name: Install autotools
          run: |
            set -x
            if test ${{ matrix.os }} == ubuntu-latest ; then
                sudo apt-get update
                sudo apt-get install autoconf
                sudo apt-get install automake
                sudo apt-get install m4

                # sudo apt-get install libtool libtool-bin
                wget -q https://ftp.gnu.org/gnu/libtool/libtool-${LIBTOOL_VERSION}.tar.gz
                gzip -dc libtool-${LIBTOOL_VERSION}.tar.gz | tar -xf -
                cd libtool-${LIBTOOL_VERSION}
                ./configure --prefix=/usr --silent
                sudo make -s LIBTOOLFLAGS=--silent V=1 -j 8 install > qout 2>&1
                sudo make -s LIBTOOLFLAGS=--silent V=1 -j 8 distclean >> qout 2>&1
            else
                brew update
                brew install coreutils
                brew install autoconf
                brew install automake
                brew install libtool
                export PATH="/opt/homebrew/opt/libtool/libexec/gnubin:${PATH}"
                brew list m4 || brew install m4
            fi
            which autoconf
            autoconf --version
            which automake
            automake --version
            which libtool
            libtool --version
            which m4
            m4 --version

        - name: Install MPI compiler vendor - ${{ matrix.mpi_vendor }}
          run: |
            if test "${{ matrix.mpi_vendor }}" = "MPICH" ; then
                # MPICH versions older than 4.2.2 do not support the MPI large
                # count feature.
                echo "Install MPICH ${MPICH_VERSION} in ${GITHUB_WORKSPACE}/MPI"
                wget -q https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz
                gzip -dc mpich-${MPICH_VERSION}.tar.gz | tar -xf -
                cd mpich-${MPICH_VERSION}
                ./configure --prefix=${GITHUB_WORKSPACE}/MPI \
                            --silent \
                            --enable-romio \
                            --with-file-system=ufs \
                            --with-device=ch3:sock \
                            --disable-fortran --disable-cxx \
                            CC=gcc
                make -s LIBTOOLFLAGS=--silent V=1 -j 8 install > qout 2>&1
                make -s LIBTOOLFLAGS=--silent V=1 -j 8 distclean >> qout 2>&1
            else # OpenMPI
                echo "Install OPENMPI ${OPENMPI_VERSION} in ${GITHUB_WORKSPACE}/MPI"
                VER_MAJOR=${OPENMPI_VERSION%.*}
                wget -q https://download.open-mpi.org/release/open-mpi/v${VER_MAJOR}/openmpi-${OPENMPI_VERSION}.tar.gz
                gzip -dc openmpi-${OPENMPI_VERSION}.tar.gz | tar -xf -
                cd openmpi-${OPENMPI_VERSION}
                if test "${{ matrix.os }}" = "macos-latest" ; then
                   # When built on MacOS, additional configure options are required.
                   EXTRA_OPTS="--with-hwloc=internal --with-pmix=internal --with-libevent=internal"
                fi
                ./configure --prefix=${GITHUB_WORKSPACE}/MPI \
                            --silent \
                            --with-io-romio-flags="--with-file-system=ufs" \
                            ${EXTRA_OPTS} \
                            --disable-mpi-fortran --disable-oshmem-fortran \
                            CC=gcc
                make -s LIBTOOLFLAGS=--silent V=1 -j 8 install > qout 2>&1
                make -s LIBTOOLFLAGS=--silent V=1 -j 8 distclean >> qout 2>&1
            fi

        - name: Clone PnetCDF and symbolic link to GIO as a submodule
          run: |
            set -x
            cd ${GITHUB_WORKSPACE}
            if test ${{ matrix.os }} == macos-latest ; then
                export PATH="/opt/homebrew/opt/libtool/libexec/gnubin:${PATH}"
            fi
            git clone https://github.com/${PNETCDF_REPO}/PnetCDF.git
            cd PnetCDF
            # git submodule update --init --recursive
            rm -rf gio ; ln -s ${GITHUB_WORKSPACE} gio
            which autoconf
            autoconf --version
            which automake
            automake --version
            which libtool
            libtool --version
            which m4
            m4 --version
            autoreconf -i

        - name: Build PnetCDF - ${{ matrix.fstype }}
          if: ${{ always() }}
          run: |
            set -x
            cd ${GITHUB_WORKSPACE}
            if test ${{ matrix.os }} == macos-latest ; then
                export PATH="/opt/homebrew/opt/libtool/libexec/gnubin:${PATH}"
            fi
            if test ${{ matrix.fstype }} == mimic_lustre ; then
                export MIMIC_LUSTRE=yes
            fi
            if test ${{ matrix.debug_mode }} == debug ; then
                CONFIG_OPTS="--enable-debug"
            else
                CONFIG_OPTS="--disable-debug"
            fi
            MPI_RUN="${GITHUB_WORKSPACE}/MPI/bin/mpiexec -n NP"
            mkdir -p ${GITHUB_WORKSPACE}/pnetcdf_output
            mkdir build ; cd build
            ${GITHUB_WORKSPACE}/PnetCDF/configure \
                        --prefix=${GITHUB_WORKSPACE} \
                        pnc_ac_debug=yes \
                        --disable-fortran --disable-cxx \
                        --enable-burst_buffering \
                        --enable-subfiling \
                        --enable-thread-safe \
                        --with-pthread \
                        ${CONFIG_OPTS} \
                        --with-mpi=${GITHUB_WORKSPACE}/MPI \
                        TESTOUTDIR=${GITHUB_WORKSPACE}/pnetcdf_output \
                        TESTMPIRUN="${MPI_RUN}"
            make -s LIBTOOLFLAGS=--silent V=1 -j 8 tests

        - name: Print config.log
          if: ${{ always() }}
          run: |
            cat ${GITHUB_WORKSPACE}/build/config.log

        - name: make check
          run: |
            cd ${GITHUB_WORKSPACE}/build
            export GIO_ONLY=1
            make -s LIBTOOLFLAGS=--silent V=1 check

        - name: Print make check log files
          if: ${{ always() }}
          run: |
            cd ${GITHUB_WORKSPACE}/build
            fname=`find src test examples benchmarks -type f -name "*.log"`
            for f in $fname ; do \
               bname=`basename $f` ; \
               if test "x$bname" != xconfig.log ; then \
                  echo "" ; \
                  echo "-------- dump $f ----------------------------" ; \
                  cat $f ; \
               fi ; \
            done

        - name: make ptests
          run: |
            cd ${GITHUB_WORKSPACE}/build
            # skip testing of MPI-IO driver (too slower)
            export GIO_ONLY=1
            make -s LIBTOOLFLAGS=--silent V=1 ptests

        - name: make install
          run: |
            set -x
            cd ${GITHUB_WORKSPACE}/build
            prefix_path=${GITHUB_WORKSPACE}/pnetcdf_install
            echo "---- test make install prefix=${prefix_path}"
            make -s LIBTOOLFLAGS=--silent V=1 install prefix=${prefix_path}
            ls -lR ${prefix_path}

            prefix_path="/pnetcdf_install"
            destdir_path=${GITHUB_WORKSPACE}/inst
            echo "---- test make install prefix=${prefix_path} DESTDIR=${destdir_path}"
            make -s LIBTOOLFLAGS=--silent V=1 install prefix=${prefix_path} DESTDIR=${destdir_path}
            ls -lR ${destdir_path}

        - name: Cleanup
          if: ${{ always() }}
          run: |
            cd ${GITHUB_WORKSPACE}/build
            make -s LIBTOOLFLAGS=--silent V=1 distclean

